## Numpy and Array Basics

The numpy library is one of the core packages in Python's data science software stack. Many other Python data analysis libraries require numpy as a prerequisite, because they use its array data structure as a building block. The Kaggle Python environment has numpy available by default; if you are running Python locally, the Anaconda Python distribution comes with numpy as well.

Numpy implements a data structure called the N-dimensional array or ndarray. ndarrays are similar to lists in that they contain a collection of items that can be accessed via indexes. On the other hand, ndarrays are homogeneous, meaning they can only contain objects of the same type and they can be multi-dimensional, making it easy to store 2-dimensional tables or matrices.

## Import NumPY Library 

In [1]:
import numpy as np 

## Creating a NumPy Array

### Basic ndarray 

In [4]:
a = [10,20,30,40]

In [5]:
type(a)

list

In [7]:
x = np.array(a)

[10 20 30 40]


In [8]:
print(x)

[10 20 30 40]


In [9]:
type(x)

numpy.ndarray

In [11]:
a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [12]:
a = [1,2,3,4]
b = [10,20,30]
x = np.array([a,b])
print(x)

[list([1, 2, 3, 4]) list([10, 20, 30])]


In [15]:
x = np.array([1,2,3,4],dtype=np.float32)
print(x)

[1. 2. 3. 4.]


In [20]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


## Array of zeros 

In [21]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
x = np.ones(4,dtype=np.int32)
print(x)

[1 1 1 1]


## Random numbers in ndarrays 

In [28]:
x = np.random.rand(2,5)
print(x)

[[0.6484605  0.81627261 0.18862262 0.72647045 0.30434428]
 [0.72961134 0.30785377 0.3520016  0.17491033 0.68197271]]


In [29]:
np.random.rand??

In [31]:
x = np.random.randint(1,20,size=(3,3))
print(x)

[[ 7  2  1]
 [13  9 14]
 [14 15 18]]


In [32]:
np.random.randint??

In [33]:
x = np.random.randn(2,5)
print(x)

[[-1.49319507  0.21542931 -1.00593883  0.08401735 -0.78755239]
 [-2.66728672 -1.21459886 -0.42252678 -0.92854207 -0.56430003]]


In [34]:
np.random.randn??

In [38]:
np.random.choice([2,3,5,6,8])

2

## An array of your choice 

In [41]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [43]:
np.ones((3,4))*10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

## Identity matrix

In [52]:
x = np.eye(4,k=-1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


np.eye??

## Evenly spaced ndarray

In [53]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [55]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [57]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Shape and Reshaping of NumPy Array 

###  Dimension of nparray 

In [59]:
a =[10,20,30,40,50]
x = np.array(a)
print(x)

[10 20 30 40 50]


In [60]:
x.ndim

1

In [64]:
b =[4,5,6,7,8]
y = np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 4  5  6  7  8]]


In [66]:
y.ndim

2

## Shape of NumPy array 

In [69]:
y.size

10

In [68]:
y.shape

(2, 5)

## Reshaping a NumPy array 

In [70]:
a = np.array([3,4,5,6])
print(a)

[3 4 5 6]


In [71]:
b = np.reshape(a,(2,2))
print(b)

[[3 4]
 [5 6]]


In [72]:
a.reshape(2,2)

array([[3, 4],
       [5, 6]])

In [73]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [74]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [75]:
x.size

15

## Transpose of a NumPy array 

In [76]:
y = np.arange(1,16)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [82]:
y = y.reshape(3,5)
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [81]:
z = np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [83]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

## Indexing and Slicing of NumPy Array 

## 1D NumPy arrays 

In [84]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
a[2:7]

array([3, 4, 5, 6, 7])

## 2-D NumPy arrays 

In [86]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
x[1,2]

6

In [88]:
x[1][2]

6

In [89]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

## Stacking and Concatenating NumPy Arrays 

## Stacking 

In [90]:
a = np.arange(1,6)
b = np.arange(6,11)
a

array([1, 2, 3, 4, 5])

In [91]:
b

array([ 6,  7,  8,  9, 10])

In [92]:
x = np.vstack((a,b))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [93]:
x = np.hstack((a,b))
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Concatenating 

In [94]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)

In [95]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [97]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [98]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

## Broadcasting in NumPy arrays 

In [100]:
a = np.arange(10,21,2)
b = np.array([[2],[2]])

In [101]:
print(a)

[10 12 14 16 18 20]


In [102]:
print(b)

[[2]
 [2]]


In [103]:
z =a+b
z

array([[12, 14, 16, 18, 20, 22],
       [12, 14, 16, 18, 20, 22]])

In [108]:
a = np.arange(10,21,2)
print(a)

[10 12 14 16 18 20]


In [109]:
a+2

array([12, 14, 16, 18, 20, 22])

In [110]:
a-2

array([ 8, 10, 12, 14, 16, 18])

In [111]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [115]:
a = np.ones((3,3))
b = np.array([2])

In [117]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [118]:
print(b)

[2]


In [116]:
z = a+b
z

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [119]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

## Arithmetic Operations on NumPy Array 

In [120]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [121]:
a+5

array([[6., 5., 5., 5.],
       [5., 6., 5., 5.],
       [5., 5., 6., 5.],
       [5., 5., 5., 6.]])

In [122]:
a-1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [123]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [124]:
a/0.5

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [125]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [126]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [127]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##  Aggregate Function

## Mean, Median and Standard deviation

In [128]:
a =np.arange(5,16,2)

In [129]:
a

array([ 5,  7,  9, 11, 13, 15])

In [130]:
np.mean(a)

10.0

In [131]:
np.std(a)

3.415650255319866

In [132]:
np.median(a)

10.0

## Min-Max values 

In [134]:
a =  np.array([[1,6],[4,3]])
a

array([[1, 6],
       [4, 3]])

In [135]:
print(np.min(a,axis=0))

[1 3]


In [136]:
print(np.min(a,axis=1))

[1 3]


In [137]:
print(np.max(a,axis=0))

[4 6]


In [138]:
print(np.max(a,axis=1))

[6 4]


## Sorting 

In [139]:
a =np.array([1,5,3,7,10,9,12])
a

array([ 1,  5,  3,  7, 10,  9, 12])

In [140]:
x = np.sort(a,kind='mergesort')
print(x)

[ 1  3  5  7  9 10 12]


## Matrix Multiplication 

In [142]:
a = np.arange(0,9).reshape(3,3)
b = np.ones((3,3))

In [143]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [145]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [146]:
np.dot(a,b)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [147]:
a.dot(b)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])